from __future__ import annotations

import pytest

from muscat_db.ephemeris_import import EphemerisCSVError, parse_transit_csv
from fastapi.testclient import TestClient

from muscat_db.web import app


ALLesFITTER_CSV = """planet,epoch,tc(BJD),tc_unc(BJD)
b,-183,2458604.024028042,0.0008107030298560858
c,-89,2458602.501682544,0.0015947530046105385
"""


def test_parses_allesfitter_ttv_headers_and_types():
    result = parse_transit_csv(ALLesFITTER_CSV)

    assert result["columns"] == {
        "planet": "planet",
        "epoch": "epoch",
        "tc": "tc(BJD)",
        "tc_unc": "tc_unc(BJD)",
    }
    assert result["rows"][0] == {
        "line": 2,
        "planet": "b",
        "source_epoch": -183,
        "tc": pytest.approx(2458604.024028042),
        "tc_unc": pytest.approx(0.0008107030298560858),
    }
    assert result["time_system"] == {
        "value": "BJD (time scale unspecified)",
        "confirmed": False,
        "supported": True,
    }


def test_accepts_export_comments_and_bjd_tdb_aliases():
    text = """# Transit Center Times in BJD_TDB
# generated by muscat-db
planet,transit_epoch,tc_bjd,tc_unc_days
b,0,2460000.1,0.001
"""
    result = parse_transit_csv(text)
    assert result["rows"][0]["source_epoch"] == 0
    assert result["time_system"] == {
        "value": "BJD_TDB", "confirmed": True, "supported": True
    }


def test_bjd_utc_is_detected_but_not_marked_safe_to_import():
    result = parse_transit_csv(
        "# time system: BJD_UTC\nplanet,epoch,tc,tc_unc\nb,0,2460000.1,0.001\n"
    )

    assert result["time_system"] == {
        "value": "BJD_UTC", "confirmed": True, "supported": False
    }
    assert "explicit time-scale conversion" in result["warnings"][0]


def test_reports_bad_rows_but_keeps_valid_rows():
    text = """planet,epoch,tc,tc_unc
b,0,2460000.1,0.001
c,1.5,nope,-1
"""
    result = parse_transit_csv(text)
    assert len(result["rows"]) == 1
    assert result["errors"] == [
        {
            "line": 3,
            "errors": [
                "tc is not a finite number",
                "tc_unc must be a positive finite number",
                "epoch must be an integer",
            ],
        }
    ]


def test_rejects_missing_required_columns():
    with pytest.raises(EphemerisCSVError, match="Missing required column.*tc_unc"):
        parse_transit_csv("planet,epoch,tc\nb,0,2460000.1\n")


def test_import_preview_endpoint_does_not_accept_server_paths():
    response = TestClient(app).post(
        "/api/ephemeris/import-csv",
        json={"filename": "../../ttv.csv", "content": ALLesFITTER_CSV},
    )

    assert response.status_code == 200
    body = response.json()
    assert body["filename"] == "ttv.csv"
    assert len(body["rows"]) == 2


def test_import_preview_endpoint_returns_actionable_parse_error():
    response = TestClient(app).post(
        "/api/ephemeris/import-csv",
        json={"filename": "bad.csv", "content": "planet,tc\nb,2460000\n"},
    )

    assert response.status_code == 400
    assert "tc_unc" in response.json()["error"]
